### ISSUE TITLE
Duplicating money

### ISSUE THREAD

**Issue by selfservice0** [graywolf336/CasinoSlots#39] opened 2013-02-01 21:28 UTC
TO duplicate money using slots:
First create a slot machine that takes all your money (lets say you have $1001)

Create the slot machine to take $1000 per spin. Deposit $1 into the slot machine (so you can spin it). Player your slot machine. It will take your $1000 if you loose. 
Withdraw the money ($1000) from the slot and restart. Repeat until you win. On win you will receive the winnings and the slot will have your $1001 inside it, thus creating the winnings from no-where.

**Comment by graywolf336** [comment] 2015-11-03 23:37
Closed via 4f62a50.

**Comment by graywolf336** [comment] 2015-11-03 23:56
Actually, just verified this issue and will be fixing it once I verify the fix is applied.

**Comment by graywolf336** [comment] 2015-11-04 00:00
The issue is fixed with d397af1, but testing would be nice.

**Closed by graywolf336** 2015-11-04 00:00 UTC
